In [1]:
import torch

In [15]:
a=torch.arange(10)
print(id(a))
a=a.reshape(2, 5)
print(id(a))
a
# 这里一般情况也不必非得地址一样，因为确实矩阵从本质上就发生了变化

140626899431568
140626899431568


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x=torch.arange(10, dtype=float)
y=torch.tensor([[0],[1]])
z=x+y  # 广播机制
z

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],
       dtype=torch.float64)

In [20]:
x.requires_grad_(True)
y.requires_grad_(True)
x.grad

In [30]:
k=(x*x).sum()
x.grad.zero_()
k.backward()   # 标量求梯度，每次会叠加！
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=torch.float64)